---
driver:
  name: docker_cli

transport:
  name: docker_cli

provisioner:
  name: ansible_playbook
  hosts: localhost
  require_ansible_repo: false
  require_ansible_omnibus: false
  require_chef_for_busser: true
  ansible_verbose: false
  ansible_inventory: ./test/integration/inventory

platforms:
  - name: debian
    driver_config:
      image: "nishiki/debian<%= ENV['DEBIAN_VERSION'] ? ENV['DEBIAN_VERSION'] : '10' %>:ansible-<%= ENV['ANSIBLE_VERSION'] ? ENV['ANSIBLE_VERSION'] : '2.9' %>"
      command: /bin/systemd
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      privileged: cap-add=SYS_ADMIN

suites:
  - name: default
