---
sudo: required
language: ruby

env:
  - DEBIAN_VERSION=9 ANSIBLE_VERSION=2.8
  - DEBIAN_VERSION=9 ANSIBLE_VERSION=2.9
  - DEBIAN_VERSION=10 ANSIBLE_VERSION=2.8
  - DEBIAN_VERSION=10 ANSIBLE_VERSION=2.9

services:
  - docker

before_install:
  - bundle install
  - sudo pip install --upgrade pip
  - sudo pip install yamllint
  - sudo pip install ansible-lint
  - git clone https://github.com/ansible/galaxy-lint-rules.git

script:
  - kitchen conv
  - kitchen conv | grep changed=0
  - kitchen verify
  - ansible-lint -r galaxy-lint-rules/rules .
  - yamllint .

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
