---
- name: Converge
  hosts: all
  vars:
    mariadb_autorestart: yes
    mariadb_master: yes
    mariadb_config:
      client-server: {}
      mysqld:
        datadir: /opt/mariadb
        server-id: 5
        log-bin: mysql-bin
    mariadb_databases:
      - name: test
    mariadb_users:
      - name: toto
        host: '%'
        password: test
        privileges:
          - 'test.*:ALL'
  roles:
    - ansible-role-mariadb
